### ISSUE TITLE
Add possibility to set test description automatically

### ISSUE THREAD

**Issue by sporitskiy** [reportportal/reportportal#152]
For today test description is used only for manual setting or for telling us about test was auto-analyzed.

It could be very useful to have possibility to write a description for failed tests that will include last error message from test log. 
So, we will not need to open every single test to see the failure reason.

For example, In our project (we automate web services testing) I grab errors/warnings from last response and log it in the end of a test, then I don't need to open the whole attached response. 
With this new functionality we will see test failures reasons without opening every test and perform group actions to them.

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu it's exactly what was discussed!

also
we need to add possibility to bypass description for launch via params.
like `rp.launch.description`
and resource to update description for `testItem`


so 3 bullets here:
 - [ ] resource method to add description for `testItem` @avarabyeu 
 - [ ] description for launch via params like `rp.launch.description` @avarabyeu 
 - [ ] add wrapper in markdown for error text @lexecon 
 - [ ] add style for error wrapper in description @Iren-Melnyk 
 - [ ] describe it in tasks and make separate tasks @ksuglotova 

**milestone 3.2**

**Comment by DzmitryHumianiuk** [comment]
@lexecon please describe `add style for error wrapper`
@pictureb00k please describe `rp.description` usage

**Comment by DzmitryHumianiuk** [comment]
@sporitskiy 

extend testItem description with 
```
```error
error_text
```
like 
![image](https://user-images.githubusercontent.com/11332788/28582474-3136a840-716e-11e7-8f4b-f2eb16f2cfbe.png)

and you will get 
![image](https://user-images.githubusercontent.com/11332788/28582491-429c03be-716e-11e7-8d49-1c12bb8d03e5.png)

**Comment by avarabyeu** [comment]
we definitely need to introduce custom annotations to be able to specify test name/description. Also, annotation should  accept placeholders to be able to build up description dynamically

**Comment by pictureb00k** [comment]
`resource method to add description for testItem on finish @avarabyeu`
descriptions and tags will be available in v3.2

**Comment by avarabyeu** [comment]
http://reportportal.io/#documentation/JVM-based-clients-configuration

**Comment by DzmitryHumianiuk** [comment]
@sporitskiy 
https://github.com/reportportal/example-java-TestNG/blob/c6b7ba8922d884e19f02480da5dbcc7bd459f0b4/logback/src/main/java/com/epam/rp/tests/extension/ParameterizedTest.java#L86
